apiVersion: v1
kind: Secret
metadata:
  name: rundeck-tls-secret
  labels:
    app: rundeck
type: kubernetes.io/tls
data:
  tls.crt: <base64-encoded-cert>
  tls.key: <base64-encoded-key>
# Use: kubectl create secret tls rundeck-tls-secret --cert=cert.pem --key=key.pem --dry-run=client -o yaml 