apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rundeck-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard 