apiVersion: v1
kind: Secret
metadata:
  name: rundeck-db-secret
  labels:
    app: rundeck
stringData:
  type: "org.postgresql.Driver"   # Replace with your DB driver
  jdbc: "jdbc:postgresql://db-host:5432/rundeck"  # Replace with your JDBC URL
  user: "rundeckuser"             # Replace with your DB username
  password: "REPLACE_ME"          # Replace with your DB password 