name: Trigger Rundeck Job (Demo)

on:
  workflow_dispatch:

jobs:
  trigger-rundeck:
    runs-on: [self-hosted, linux]
    steps:
      - name: Trigger Rundeck Job
        run: |
          curl -X POST "https://rundeck-prod.internal.trailways.com/api/36/job/JOB_ID/run" \
            -H "X-Rundeck-Auth-Token: ${{ secrets.RUNDECK_TOKEN }}" 
